stages:
  - sync

sync_from_github:
  stage: sync
  script:
    - git remote add github https://github.com/Pavel333333/Fastapi_itm.git
    - git fetch github
    - git checkout main
    - git reset --hard github/master
    - git push origin main
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'