stages: [.pre, build, test, deploy, .post]

build-job:
  stage: build
  script:
    - docker build -t app_fastapi_itm .
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

test-job:
  stage: test
  script:
    # Создаем файл с переменной окружения для базы данных
    - echo "DATABASE_URL=postgres://test_user:test_pass@test_db:5432/test_db" > .env-not-dev
    # Запускаем тестовую базу данных
    - docker compose up -d test_db
    # Ожидаем готовности базы
    - |
      until docker run --rm --network fastapi_default postgres:17 pg_isready -h test_db -U test_user; do
        echo "Waiting for test_db to be ready..."
        sleep 2
      done
    # Очищаем схему public перед загрузкой дампа
    - docker run --rm -i -e PGPASSWORD=test_pass --network fastapi_default postgres:17 psql -h test_db -U test_user -d test_db -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"
    # Фильтруем дамп от transaction_timeout и загружаем его
    - |
      cat $CI_PROJECT_DIR/fastapi_itm_test_dump.sql | \
      grep -v "transaction_timeout" | \
      docker run --rm -i -e PGPASSWORD=test_pass --network fastapi_default postgres:17 psql -h test_db -U test_user -d test_db
    # Удаляем старый контейнер и создаем новый с нужными переменными окружения
    - |
      docker rm -f test_container || true  # Удаляем старый контейнер, если есть
      docker run -d --name test_container --network fastapi_default \
        -e "MODE=TEST" \
        -e "DB_USER=test_user" \
        -e "DB_PASSWORD=test_pass" \
        -e "DB_HOST=test_db" \
        -e "DB_PORT=5432" \
        -e "DB_NAME=test_db" \
        -e "RABBITMQ_HOST=rabbitmq" \
        -e "RABBITMQ_USER=guest" \
        -e "RABBITMQ_PASS=guest" \
        -e "TEST_DB_USER=test_user" \
        -e "TEST_DB_PASSWORD=test_pass" \
        -e "TEST_DB_HOST=test_db" \
        -e "TEST_DB_PORT=5432" \
        -e "TEST_DB_NAME=test_db" \
        python:3.11 tail -f /dev/null
      docker cp $CI_PROJECT_DIR/requirements.txt test_container:/requirements.txt
      docker cp $CI_PROJECT_DIR/app test_container:/app
      docker exec test_container sh -c "apt-get update && apt-get install -y python3-pip && pip install -r /requirements.txt && pip install pytest"
      docker exec test_container sh -c "pytest -v /app/tests"
      docker stop test_container
      docker rm test_container
    # Останавливаем тестовую базу
    - docker compose down
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

deploy-job:
  stage: deploy
  environment: production
  script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - cat "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh && ssh-keyscan -H 176.123.165.243 >> ~/.ssh/known_hosts
    - scp docker-compose.yml admin@176.123.165.243:/home/admin/fastapi_itm/
    - ssh admin@176.123.165.243 "cd /home/admin/fastapi_itm && echo DATABASE_URL=\$DATABASE_URL > .env-not-dev"
    - ssh admin@176.123.165.243 "cd /home/admin/fastapi_itm && echo RABBITMQ_URL=\$RABBITMQ_URL >> .env-not-dev"
    - ssh admin@176.123.165.243 "cd /home/admin/fastapi_itm && docker compose down && docker compose up -d --build"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'