# MODE обязателен для каждой job: "TEST" для тестов, "DEV" для деплоя

stages:
  - build
  - test
  - deploy

# Build job: Сборка Docker-образа
build-job:
  stage: build
  script:
    - docker build -t app_fastapi_itm .
  tags:
    - fastapi_itm
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

# Test job: Запуск тестов
test-job:
  stage: test
  script:
    - docker compose down -v  # Очистка перед запуском, если что-то осталось
    - docker build --no-cache -t app_fastapi_itm .  # Добавлено: пересборка образа для актуального app.sh
    - echo "TEST_DB_USER=$TEST_DB_USER, TEST_DB_PASSWORD=$TEST_DB_PASSWORD, TEST_DB_NAME=$TEST_DB_NAME"
    - MODE=$MODE TEST_DB_HOST=$TEST_DB_HOST TEST_DB_PORT=$TEST_DB_PORT TEST_DB_NAME=$TEST_DB_NAME TEST_DB_USER=$TEST_DB_USER TEST_DB_PASSWORD=$TEST_DB_PASSWORD DB_HOST=$DB_HOST DB_PORT=$DB_PORT DB_NAME=$DB_NAME DB_USER=$DB_USER DB_PASSWORD=$DB_PASSWORD RABBITMQ_HOST=$RABBITMQ_HOST RABBITMQ_USER=$RABBITMQ_USER RABBITMQ_PASS=$RABBITMQ_PASS APP_URL=$APP_URL docker compose up -d test_db app_fastapi celery
    - sleep 89
    - docker ps -a  # Проверяем состояние контейнеров
    - docker exec container_fastapi_app nc -zv container_fastapi_db_test 5434 || echo "Port 5434 not accessible"
    - docker exec container_fastapi_celery nc -zv container_fastapi_rabbitmq 5672
    - docker logs container_fastapi_app  # Логи app
    - docker logs container_fastapi_celery  # Логи celery
    - if [ "$(docker inspect -f '{{.State.Running}}' container_fastapi_app)" != "true" ]; then echo "App container not running"; exit 1; fi
    - docker exec container_fastapi_app pytest -s -v
    - docker compose down -v  # Очистка после тестов
  variables:
    MODE: "TEST"
    TEST_DB_HOST: "container_fastapi_db_test"
    TEST_DB_PORT: "5434"
    TEST_DB_NAME: "fastapi_itm_test"
    DB_HOST: "container_fastapi_db"  # Добавлено, чтобы тест контейнер не падал
    DB_PORT: "5433"                  # Добавлено, чтобы тест контейнер не падал
    DB_NAME: "fastapi_itm_db"        # Добавлено, чтобы тест контейнер не падал
    RABBITMQ_HOST: "container_fastapi_rabbitmq"
    RABBITMQ_USER: "admin"
    RABBITMQ_PASS: "admin"
    RABBITMQ_VHOST: "fastapi_itm_vhost"
    APP_URL: "http://localhost:3333"
  tags:
    - fastapi_itm
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

# Deploy job: Развертывание приложения
deploy-job:
  stage: deploy
  script:
    - ssh pavel@82.202.138.125 "cd /home/pavel/dev/fastapi_itm && docker compose down && docker image prune -f && docker network prune -f && MODE=$MODE DB_HOST=$DB_HOST DB_PORT=$DB_PORT DB_NAME=$DB_NAME RABBITMQ_HOST=$RABBITMQ_HOST RABBITMQ_USER=$RABBITMQ_USER RABBITMQ_PASS=$RABBITMQ_PASS APP_URL=$APP_URL docker compose up -d --build"
  variables:
    MODE: "DEV"
    DB_HOST: "container_fastapi_db"
    DB_PORT: "5433"
    DB_NAME: "fastapi_itm_db"
    RABBITMQ_HOST: "container_fastapi_rabbitmq/fastapi_itm_vhost"
    RABBITMQ_USER: "admin"
    RABBITMQ_PASS: "admin"
    APP_URL: "http://localhost:3333"
  tags:
    - fastapi_itm
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'