stages: [.pre, build, test, deploy, .post]

build-job:
  stage: build
  script:
    - docker build -t app_fastapi_itm .
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

test-job:
  stage: test
  script:
    - docker stop test_container || true
    - docker rm -f test_container || true
    - docker run -d --name test_container -e "MODE=TEST" -e "TEST_DB_TYPE=sqlite" -e "TEST_DB_PATH=/app/test.db" -e "PATH_TO_FILES=/app/documents_for_tests" python:3.12 tail -f /dev/null
    - docker exec test_container sh -c "mkdir -p /app"
    - docker cp $CI_PROJECT_DIR/requirements.txt test_container:/app/requirements.txt
    - docker cp $CI_PROJECT_DIR/app test_container:/app
    - docker cp $CI_PROJECT_DIR/app/tests test_container:/app/tests
    - docker exec test_container sh -c "ls -la /app"
    - docker exec test_container sh -c "cat /app/main.py || echo 'Error: main.py not found or empty'"
    - docker exec test_container sh -c "mkdir -p /app/documents_for_tests"
    - docker exec test_container sh -c "apt-get update && apt-get install -y python3-pip netcat-openbsd curl && pip install -r /app/requirements.txt && pip install pytest uvicorn"
    - docker exec -d test_container sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8001 --log-level debug > /tmp/uvicorn.log 2>&1"
    - sleep 5
    - >-
      if docker exec test_container nc -z localhost 8001; then
        echo "FastAPI server is ready!";
      else
        echo "FastAPI server failed to start!";
        docker exec test_container sh -c "cat /tmp/uvicorn.log";
        exit 1;
      fi
    - docker exec test_container sh -c "curl -X POST -F 'file=@/app/tests/test_files/fgh.jpeg' -s http://localhost:8001/files/upload_doc"
    - docker exec test_container sh -c "pytest -v /app/tests"
    - docker stop test_container || true
    - docker rm -f test_container || true
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

deploy-job:
  stage: deploy
  environment: production
  script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - cat "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh && ssh-keyscan -H 176.123.165.243 >> ~/.ssh/known_hosts
    - scp docker-compose.yml admin@176.123.165.243:/home/admin/fastapi_itm/
    - ssh admin@176.123.165.243 "cd /home/admin/fastapi_itm && echo DATABASE_URL=\$DATABASE_URL > .env-not-dev"
    - ssh admin@176.123.165.243 "cd /home/admin/fastapi_itm && echo RABBITMQ_URL=\$RABBITMQ_URL >> .env-not-dev"
    - ssh admin@176.123.165.243 "cd /home/admin/fastapi_itm && docker compose down && docker compose up -d --build"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'