stages:
  - build
  - test
  - deploy

variables:
  POSTGRES_DB: fastapi_itm_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  TEST_DB_HOST: postgres
  TEST_DB_PORT: 5432
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_USER: guest
  RABBITMQ_PASS: guest

# Build job: Сборка Docker-образа
build-job:
  stage: build
  image: ubuntu:24.04  # Используем Ubuntu 24.04 LTS
  script:
    # Обновление и установка зависимостей
    - apt-get update && apt-get install -y docker.io
    # Собираем Docker-образ
    - docker build -t app_fastapi_itm .
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

test-docker:
  stage: test
  script:
    - docker --version
    - docker ps
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

print-env:
  stage: test
  script:
    - env | grep DOCKER
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'