stages: [.pre, build, test, deploy, .post]

build-job:
  stage: build
  script:
    - docker build -t app_fastapi_itm .
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

test-job:
  stage: test
  script:
    # Создаем переменную окружения для базы данных
    - echo "DATABASE_URL=postgres://test_user:test_pass@test_db:5432/test_db" > .env-not-dev
    # Запускаем тестовую базу данных
    - docker compose up -d test_db
    # Ожидаем готовности базы данных
    - |
      until docker run --rm --network fastapi_default postgres:17 pg_isready -h test_db -U test_user; do
        echo "Waiting for test_db to be ready..."
        sleep 2
      done
    # Проверяем версию PostgreSQL для отладки
    - docker run --rm postgres:17 psql --version
    # Очищаем схему public перед загрузкой дампа
    - docker run --rm -i -e PGPASSWORD=test_pass --network fastapi_default postgres:17 psql -h test_db -U test_user -d test_db -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"
    # Загружаем дамп в базу данных
    - |
      cat $CI_PROJECT_DIR/fastapi_itm_test_dump.sql | \
      docker run --rm -i -e PGPASSWORD=test_pass --network fastapi_default postgres:17 psql -h test_db -U test_user -d test_db
    # Запускаем тесты с использованием Python-образа
    - |
      docker run --rm \
        -e DATABASE_URL=postgres://test_user:test_pass@test_db:5432/test_db \
        -e MODE=TEST \
        -v $CI_PROJECT_DIR/app:/app \  # Монтируем app/, где код и requirements.txt
        --network fastapi_default \
        python:3.11 \
        sh -c "apt-get update && apt-get install -y python3-pip && pip install -r /app/requirements.txt && pip install pytest && pytest -v /app/tests/"
    # Останавливаем тестовую базу данных
    - docker compose down
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

deploy-job:
  stage: deploy
  environment: production
  script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - cat "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh && ssh-keyscan -H 176.123.165.243 >> ~/.ssh/known_hosts
    - scp docker-compose.yml admin@176.123.165.243:/home/admin/fastapi_itm/
    - ssh admin@176.123.165.243 "cd /home/admin/fastapi_itm && echo DATABASE_URL=\$DATABASE_URL > .env-not-dev"
    - ssh admin@176.123.165.243 "cd /home/admin/fastapi_itm && echo RABBITMQ_URL=\$RABBITMQ_URL >> .env-not-dev"
    - ssh admin@176.123.165.243 "cd /home/admin/fastapi_itm && docker compose down && docker compose up -d --build"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'