stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t app_fastapi_itm .

test-job:
  stage: test
  script:
    - docker run --rm app_fastapi_itm pytest -s -v

deploy-job:
  stage: deploy
  environment: production
  script:
    - docker compose up -d